apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea-operator
  template:
    metadata:
      labels:
        name: gitea-operator
    spec:
      serviceAccountName: gitea-operator
      containers:
        - name: gitea-operator
          image: quay.io/integreatly/gitea-operator:master
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - gitea-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitea-operator"
            - name: TEMPLATE_PATH
              value: "/usr/local/bin/templates"
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 200Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /user/login
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
